### PR TITLE
Support jobs triggered by Multijobs

### LINKED ISSUE #138: Jeeves fails when configuration contains a job that was trigger by multijob
When running jeeves with a config that has a job triggered by multijob I get the following error:

``` Traceback (most recent call last):
  File "jeeves.py", line 65, in <module>
    run_report(config, blockers, server, header, test_email, no_email)
  File "/home/itbrown/git/jeeves/report.py", line 135, in run_report
    summary['total_success'] = "Total SUCCESS:  {}/{} = {}%".format(num_success, num_jobs, percent(num_success, num_jobs))
  File "/home/itbrown/git/jeeves/functions.py", line 314, in percent
    return round(100 * float(part) / float(whole), 1)
ZeroDivisionError: float division by zero```

### PR DESCRIPTION
**Pull request by itzikb**
Fix #138

### CODE REVIEW

**Comment by itzikb** [comment]
@nathan-weinberg , It's the same symptoms but not the same reason.
In this case of a job that was triggered by Multijob the _class of the action should be com.tikal.jenkins.plugins.multijob.MultiJobParametersAction

> Hi @itzikb,
> 
> Issue #138 is a dup of #117; the issue isn't multijobs but the way the summary is calculated - that's where the fix needs to be. I have it assigned to myself but if you would prefer to do it I am happy to reassign the original issue to you and we can use this PR for the fix.
> 
> Keep in mind the following as well:
> 
> * PR title should explain what is done
> * PR description should link to relevant issue
> * The commit itself seems to not be linked to your GitHub account

**Comment by nathan-weinberg** [comment]
@itzikb Could you provide a little more info, the config you used, etc?

You're the first I've heard of having issues with multijobs, but if it is the case I will unmark #138 as a dup and reopen

> @nathan-weinberg , It's the same symptoms but not the same reason.
> In this case of a job that was triggered by Multijob the _class of the action should be com.tikal.jenkins.plugins.multijob.MultiJobParametersAction
> 
> > Hi @itzikb,
> > Issue #138 is a dup of #117; the issue isn't multijobs but the way the summary is calculated - that's where the fix needs to be. I have it assigned to myself but if you would prefer to do it I am happy to reassign the original issue to you and we can use this PR for the fix.
> > Keep in mind the following as well:
> > 
> > * PR title should explain what is done
> > * PR description should link to relevant issue
> > * The commit itself seems to not be linked to your GitHub account

**Comment by itzikb** [comment]
@nathan-weinberg  What info do you need? I can give you a job name to check if you want

**Comment by nathan-weinberg** [comment]
@itzikb Just the scenario you tested that resulted in the bug and the report it produced, if possible

**Comment by itzikb** [comment]
@nathan-weinberg It was a single job that was triggered by a multijob. The program exited with an error so no report was produced.

**Comment by nathan-weinberg** [comment]
@itzikb And what was the config used?

**Comment by nathan-weinberg** [comment]
@itzikb The latest Enterprise report is populated by jobs are run via phase3 trigger: http://otter96.desklab.eng.bos.redhat.com/latest_enterprise

**Comment by itzikb** [comment]
@nathan-weinberg Do you mean jeeves config? It's similar to the example config. 
Note that the multijob that triggered the job is using the Multijob plugin (https://plugins.jenkins.io/jenkins-multijob-plugin/) and not a customized groovy code.

**Comment by nathan-weinberg** [comment]
@itzikb I need a reproduction of the bug to verify it is not a duplicate, which at the bare minimum in the `config.yaml` file you used that resulted in the bug and ideally also a copy of the report with the incorrect jobs included

**Comment by nathan-weinberg** [comment]
Hi @itzikb I investigated the bug and this is indeed a valid issue/PR. I have linked the two together and edited the title - please update the base branch with the latest changes from master and ensure the commit itself is linked to your actual GitHub account, and then we will proceed with the review. Thanks!

**Pull request merged**
