### PR TITLE
Move test requirements.

### PR DESCRIPTION
**Pull request by damani42**
Move the test requirements in a specific file. An end user does not need
to install test dependecies. The pytest dependency has been updated and requires python 3.7 or higher. There are distributions that still package
python 3.6.

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@damani42 
1. you need to fix your commit tree for this PR
2. what is the motivation for this change? you've included zero details in the description, please review https://github.com/nathan-weinberg/jeeves/blob/master/docs/CONTRIBUTING.md and make sure you are following the process

**Comment by mcgonago** [comment]
Hi Daniel - I reviewed the change. I hit the problem when jeeves recently went to using pytest 7.1.1 - while my python3 was at 3.6.7. Turns out - pytest 7.1.1 requires python3 to be at 3.7.X. For my needs - I do not run unit tests (pytest) - therefore, having pytest removed from requirements.txt allows me to continue. Otherwise, I would have needed to update to a later version of python3 - which was not available with my RHEL linux distro/version.

**Comment by damani42** [comment]
Hi @nathan-weinberg 👋,

Yes sorry for the bad git tree, you're right. I have fixed it. About the description, I have updated too. Like I have explained an end-user does not requires test dependancies.

**Review by agarcia64 — APPROVED** [review]
LGTM, thank you @damani42!

**Pull request merged**
