### PR TITLE
Extend filtering mechanism with build cause action filter

### PR DESCRIPTION
**Pull request by ciecierski**
This pr adds new build filter option. It enables to filter jobs by hudson.model.CauseAction field. 
This field contains information who triggered build. It can by either timer,user or other jenkins job(upstream).
It can be used in combination of existing param filter mechanism.

Signed-off-by: ciecierski <mciecier@redhat.com>

### CODE REVIEW

**Review by agarcia64 — COMMENTED** [review]
Tested on my local machine, everything is working as expected and the code looks good to me. I'll approve after the nits have been fixed .

**Review by nathan-weinberg — APPROVED** [review]
Works for Enterprise

**Review by odyssey4me — APPROVED** [review]

**Comment by odyssey4me** [comment]
@agarcia64 Can you do a final review and merge?

**Review by agarcia64 — APPROVED** [review]
Re-tested and re-reviewed. Everything is working as expected and the code looks good to me!

**Pull request merged**
